import { chromium } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
import path from 'node:path';

const dir=path.resolve('submission/video'), tmp=path.join(dir,'.render');
mkdirSync(tmp,{recursive:true});
const ff='/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/imageio_ffmpeg/binaries/ffmpeg-macos-aarch64-v7.1';
const scenes=[
['OPEN','Would this hoodie fit?','seed','Imagine finding a secondhand hoodie you love, but the listing says only medium. Muslin starts with a better question: how does it compare with the hoodie you already wear? This opening is a product preview using clearly labeled sample measurements.'],
['PROBLEM','A size label is not a measurement.','SIZE: M','A medium from one brand can fit differently from a medium from another. That uncertainty matters even more for secondhand clothes, where returns may be limited and sellers often measure items by hand. Buyers need a reference they understand: the garments already in their own closet.'],
['IDEA','Your closet becomes the size chart.','01 MEASURE\n02 KEEP\n03 COMPARE','Muslin has three steps. First, measure a flat garment beside a standard sheet of paper. Second, keep the clothes that fit as personal reference items. Third, compare a seller listing dimension by dimension. A simple verdict helps, but the underlying centimetre differences stay visible.'],
['BUILD','A local vision pipeline.','src/cv/pipeline.ts\n\npaper → plane\n→ garment → landmarks\n→ value ± uncertainty','The technical core is written in TypeScript and organized as pure functions. It accepts image pixels, detects the reference sheet, corrects perspective, separates the garment from the floor, estimates landmarks, and reports measurements with uncertainty. This pipeline exists in source code today. The browser interface currently uses seeded values for its visual preview.'],
['BUILD','Paper sets the scale.','LETTER: 216 × 279 MM\nA4: 210 × 297 MM\n\n4 CORNERS → FLAT PLANE','A sheet of Letter or A four paper provides a known size. The paper detector looks for a light quadrilateral. The geometry module maps four corners into a flat plane, so distances can be estimated even when the camera is angled. Detection confidence and aspect mismatch are represented as warnings.'],
['BUILD','From pixels to measurements.','FLOOR MODEL\n↓\nGARMENT CONTOUR\n↓\nPITS / HEM / SLEEVES\n↓\nMEASUREMENT RANGE','The garment stage models the surrounding floor, thresholds the difference, and traces a contour. Landmark code searches that contour for points such as shoulders, pits, hem, and sleeve ends. The measurement module returns a value and a plus or minus range. Photo accuracy still needs validation on varied real garments.'],
['DEMO','Start with a known garment.','demo-measure','Now for the live browser flow. I am opening the measurement preview. These are seeded sample values, not measurements computed from a photo in this interface. The tags show the intended result: pit to pit, length, shoulder, and sleeve, each with an uncertainty label instead of false precision.'],
['DEMO','Read the measurement tags.','demo-preview','The preview puts dimensions over the garment shape, then repeats them in a readable list. A shopper can understand what each number refers to. For a production release, this screen needs to connect to the vision pipeline and let the person correct detected endpoints. The current preview makes the experience testable while that integration remains open.'],
['DEMO','Compare the listing.','demo-fit','I move to the fit check and enter measurements from a seller listing. The reference is my favourite hoodie. Muslin shows two silhouettes and gives differences for chest, length, shoulder, and sleeve. This listing is just over two centimetres wider through the chest. That is more useful than the word medium.'],
['DEMO','Change a number. See the consequence.','demo-change','If the seller corrects the chest measurement, the difference updates immediately. The same works for length and shoulder. The verdict is deliberately simple, and detailed values remain on screen. A buyer can decide whether a looser chest is welcome, instead of relying on an opaque fit score.'],
['DEMO','The rack holds the reference.','demo-closet','The rack shows three sample garments with different measurements. Selecting another one changes what the listing is compared against. These examples live in the browser interface. Persistent personal closet storage has not been implemented yet. That is a clear next step before this can serve real shoppers.'],
['SCALE','Compute on the device.','USER DEVICE\n├ IMAGE PROCESSING\n├ PERSONAL RACK\n└ FIT COMPARISON','The planned architecture performs image processing on a buyer or seller device. That avoids uploading personal closet photos and means more users do not require more image processing servers. A public listing link would need a compact shareable measurement record. Validation, accessibility, and performance work would be needed before a wider launch.'],
['BUSINESS','Free for buyers. Tools for sellers.','BUYERS → FREE\nSELLERS → PRO TOOLS\n\nPRICING IS A HYPOTHESIS','The proposed business model keeps buyer comparison free. Sellers could pay for batch measurement, reusable listing text, and exports. Those paid tools are a roadmap, not features in this prototype. Before pricing, I would test whether sellers save enough time to pay and whether buyers trust the measurements enough to use them.'],
['CLOSE','Make uncertainty visible.','BETTER INFORMATION.\nCLEARER UNCERTAINTY.\n\nRISHIK RONTALA','Muslin cannot promise a perfect fit. Fabric stretch, drape, body shape, and seller errors still matter. It can replace a vague size label with a comparison against clothes someone already knows. This prototype demonstrates that decision flow and a separate vision core, with remaining integration work stated plainly. Built by Rishik Rontala.']
];
function dur(file){try{execFileSync(ff,['-i',file],{stdio:'pipe'})}catch(e){const m=String(e.stderr).match(/Duration: (\d+):(\d+):(\d+\.\d+)/);if(m)return +m[1]*3600 + +m[2]*60 + +m[3]}throw Error('Duration unavailable '+file)}
function voices(rate){return scenes.map((s,i)=>{const f=path.join(tmp,`voice-${i}.aiff`);execFileSync('say',['-v','Samantha','-r',String(rate),'-o',f,s[3]]);return dur(f)})}
let rate=150, lengths=voices(rate), base=lengths.reduce((a,b)=>a+b+1.3,0);
if(base>293||base<275){rate=Math.round(rate*base/283);lengths=voices(rate);base=lengths.reduce((a,b)=>a+b+1.3,0)}
if(base>300)throw Error(`Narration exceeds five minutes: ${base}`);
const times=lengths.map(x=>x+1.3+(300-base)/scenes.length);
const stamp=t=>`${String(Math.floor(t/3600)).padStart(2,'0')}:${String(Math.floor(t%3600/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')},${String(Math.round((t%1)*1000)).padStart(3,'0')}`;
let offset=0,n=0;const cues=[];
for(let i=0;i<scenes.length;i++){const parts=scenes[i][3].match(/[^.!?]+[.!?]+/g)||[scenes[i][3]];const sum=parts.reduce((a,x)=>a+x.length,0);let t=offset;for(const part of parts){const end=t+lengths[i]*part.length/sum;cues.push(`${++n}\n${stamp(t)} --> ${stamp(end)}\n${part.trim()}\n`);t=end}offset+=times[i]}
writeFileSync(path.join(tmp,'captions.srt'),cues.join('\n'));
writeFileSync(path.join(dir,'VIDEO-SCRIPT.md'),'# Muslin — five-minute demo narration\n\nSynthetic narration. The browser preview uses seeded sample values; the vision pipeline is separate and is not wired to the UI.\n\n'+scenes.map((s,i)=>`## ${s[0]} — ${s[1]}\n\n${s[3]}`).join('\n\n')+'\n');
console.log(`Narration: ${rate} words/min, ${base.toFixed(1)} seconds plus scene spacing = 300 seconds`);
if(process.argv.includes('--prepare'))process.exit(0);
const browser=await chromium.launch({headless:true});
const ctx=await browser.newContext({viewport:{width:1280,height:720},recordVideo:{dir:tmp,size:{width:1280,height:720}}});
const page=await ctx.newPage();await page.goto('http://127.0.0.1:5174/');
if(!(await page.locator('button').allTextContents()).some(x=>x.includes('SEEDED PREVIEW')))throw Error('Rehearsal: preview missing');
await page.getByText('VIEW SEEDED PREVIEW').click();
if(!(await page.locator('.stagefoot').textContent()).includes('NOT CONNECTED'))throw Error('Rehearsal: disclosure missing');
await page.getByText('03 FIT CHECK').click();if(await page.locator('.inputs input').count()!==4)throw Error('Rehearsal: fit inputs missing');
await page.getByText('02 CLOSET').click();if(await page.locator('.rackitem').count()!==3)throw Error('Rehearsal: rack missing');
await page.reload();console.log('Rehearsal passed');
await page.evaluate(()=>{const css=document.createElement('style');css.textContent='#story{position:fixed;inset:0;z-index:10000;background:#eef1ee;color:#111311;padding:48px 65px;display:grid;grid-template-columns:1fr .82fr;gap:38px;font-family:Arial,sans-serif}#story:before{content:"";position:absolute;top:0;left:0;width:22px;height:100%;background:#dcff3a}#story .phase{font:700 15px monospace;letter-spacing:.14em}#story h1{font:800 84px/.9 "Big Shoulders Display",sans-serif;text-transform:uppercase;letter-spacing:-.02em;margin:68px 0 30px}#story p{font-size:25px;line-height:1.25;max-width:580px}#story .panel{background:#111311;color:#dcff3a;padding:30px;display:flex;align-items:center;font:700 26px/1.55 monospace;white-space:pre-line}#story footer{position:absolute;bottom:28px;left:65px;right:65px;border-top:1px solid #111311;padding-top:15px;font:700 13px monospace;display:flex;justify-content:space-between}#demo-cursor{position:fixed;z-index:20000;pointer-events:none;font:40px Arial;color:white;text-shadow:2px 2px #111}';document.head.append(css);const cursor=document.createElement('div');cursor.id='demo-cursor';cursor.textContent='↖';document.body.append(cursor);document.addEventListener('mousemove',e=>{cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'})});
async function slide(s){await page.evaluate(s=>{document.getElementById('story')?.remove();const e=document.createElement('div');e.id='story';e.innerHTML=`<div><div class="phase">${s[0]} / MUSLIN</div><h1>${s[1]}</h1><p>${s[3].split('.').slice(0,2).join('.') }.</p></div><div class="panel">${s[2]}</div><footer><span>LUMA HACKATHON 2026</span><span>BUILT BY RISHIK RONTALA</span></footer>`;document.body.append(e)},s)}
async function click(t){const e=page.getByText(t).first();await e.scrollIntoViewIfNeeded();const box=await e.boundingBox();if(box)await page.mouse.move(box.x+box.width/2,box.y+box.height/2,{steps:15});await page.waitForTimeout(400);await e.click()}
for(let i=0;i<scenes.length;i++){const s=scenes[i], start=Date.now(),v=s[2];
 if(v==='demo-measure'){await page.evaluate(()=>document.getElementById('story')?.remove());await click('01 MEASURE');await page.evaluate(()=>window.scrollTo({top:450,behavior:'smooth'}))}
 else if(v==='demo-preview'){await click('VIEW SEEDED PREVIEW');await page.evaluate(()=>window.scrollTo({top:450,behavior:'smooth'}))}
 else if(v==='demo-fit'){await click('03 FIT CHECK');await page.evaluate(()=>window.scrollTo({top:430,behavior:'smooth'}))}
 else if(v==='demo-change'){const e=page.locator('.inputs input').first();await e.click();await e.fill('62.0');await page.waitForTimeout(2500);await e.fill('57.5')}
 else if(v==='demo-closet'){await click('02 CLOSET');await page.evaluate(()=>window.scrollTo({top:420,behavior:'smooth'}));await page.waitForTimeout(1500);await click('Boxy vintage tee')}
 else await slide(s);
 const remain=times[i]*1000-(Date.now()-start);if(remain>0)await page.waitForTimeout(remain);console.log(`${i+1}/${scenes.length} ${s[0]} ${times[i].toFixed(1)}s`)
}
await ctx.close();copyFileSync(await page.video().path(),path.join(tmp,'silent.webm'));await browser.close();
const files=[];for(let i=0;i<scenes.length;i++){const f=path.join(tmp,`audio-${i}.m4a`);execFileSync(ff,['-y','-i',path.join(tmp,`voice-${i}.aiff`),'-af','apad','-t',times[i].toFixed(3),'-c:a','aac','-b:a','160k',f],{stdio:'pipe'});files.push(`file '${f}'`)}
writeFileSync(path.join(tmp,'list.txt'),files.join('\n'));execFileSync(ff,['-y','-f','concat','-safe','0','-i',path.join(tmp,'list.txt'),'-c','copy',path.join(tmp,'voice.m4a')],{stdio:'pipe'});
execFileSync(ff,['-y','-i',path.join(tmp,'silent.webm'),'-i',path.join(tmp,'voice.m4a'),'-vf',`subtitles=${path.join(tmp,'captions.srt')}:force_style='FontName=Arial,FontSize=21,BorderStyle=3,BackColour=&HAA111111,MarginV=14'`,'-t','300','-c:v','libx264','-preset','fast','-crf','21','-pix_fmt','yuv420p','-c:a','aac','-b:a','160k','-movflags','+faststart',path.join(dir,'demo.mp4')],{stdio:'pipe'});
console.log('Finished',path.join(dir,'demo.mp4'),dur(path.join(dir,'demo.mp4')));
