import { chromium } from '@playwright/test';
import fs from 'node:fs';
const out='submission/video'; fs.mkdirSync(out,{recursive:true});
const b=await chromium.launch({headless:true});
const c=await b.newContext({viewport:{width:1280,height:720},recordVideo:{dir:out,size:{width:1280,height:720}}});
const p=await c.newPage();
await p.goto('http://127.0.0.1:5173/');
await p.evaluate(()=>{const s=document.createElement('style');s.textContent='#demo-sub{position:fixed;bottom:24px;left:10%;right:10%;z-index:99999;background:#111311eF;color:#DCFF3A;padding:14px 20px;text-align:center;font:700 17px monospace;letter-spacing:.02em}#demo-cursor{position:fixed;z-index:100000;pointer-events:none;font-size:28px;color:white;text-shadow:1px 1px 2px #000}';document.head.append(s);const sub=document.createElement('div');sub.id='demo-sub';document.body.append(sub);const cur=document.createElement('div');cur.id='demo-cursor';cur.textContent='↖';document.body.append(cur);document.addEventListener('mousemove',e=>{cur.style.left=e.clientX+'px';cur.style.top=e.clientY+'px'});});
const sub=async t=>{await p.locator('#demo-sub').evaluate((e,x)=>e.textContent=x,t);await p.waitForTimeout(4000)};
const move=async loc=>{const e=p.locator(loc).first();await e.scrollIntoViewIfNeeded();const box=await e.boundingBox();if(box)await p.mouse.move(box.x+box.width/2,box.y+box.height/2,{steps:15});await p.waitForTimeout(600);await e.click();await p.waitForTimeout(2200)};
await sub('THE PROBLEM — secondhand listings rarely tell you whether the garment will fit.');
await sub('THE IDEA — Muslin measures the clothes you already trust, then compares any listing to them.');
await sub('01 / MEASURE — all processing is designed to run on the device, with uncertainty shown.');
await move('button:has-text("USE DEMO PHOTO")');
await sub('The wow moment: one flat-lay photo becomes four readable measurements.');
await p.waitForTimeout(9000);
await move('button:has-text("COMPARE TO YOUR RACK")');
await sub('03 / FIT CHECK — paste seller measurements and see the difference against a real favourite.');
for(const [sel,val] of [['input','58.3'],['input','69.2'],['input','49.1'],['input','61.0']]){const e=p.locator(sel).nth(['58.3','69.2','49.1','61.0'].indexOf(val));await e.click();await e.fill(val);await p.waitForTimeout(1200)}
await sub('The overlay gives a verdict, then explains every dimension in centimetres.');
await p.waitForTimeout(9000);
await move('button:has-text("YOUR RACK")');
await sub('02 / YOUR RACK — saved garments stay local to this browser.');
await p.waitForTimeout(9000);
await move('button:has-text("Boxy vintage tee")');
await sub('Switch the reference garment and the same fit check recalculates instantly.');
await p.waitForTimeout(7000);
await sub('HOW IT WORKS — paper detection, perspective correction, segmentation, landmarks, and uncertainty.');
await p.waitForTimeout(12000);
await sub('BUSINESS — buyers are free; sellers can subscribe for batch measurement and listing exports.');
await p.waitForTimeout(12000);
await sub('SCALABILITY — compute stays on the user device, so each additional user adds almost no server cost.');
await p.waitForTimeout(12000);
await sub('LIMITATION — a measurement is not a guarantee: stretch, drape, body shape, and seller error still matter.');
await p.waitForTimeout(10000);
await sub('MUSLIN — fit before you buy. Built by Rishik Rontala.');
await p.waitForTimeout(12000);
await c.close();const src=await p.video().path();fs.copyFileSync(src,'submission/video/demo.webm');await b.close();
